Fix more secret stuff, improve scripts

diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -1,8 +1,16 @@
 #!/bin/bash
 
-OUT_FILE=$1
+# Extract version from TOC file
+VERSION=$(grep "^## Version:" src/Soundtrack/Soundtrack-Mainline.toc | sed 's/^## Version: *//')
 
-rm $OUT_FILE
+if [ -z "$VERSION" ]; then
+  echo "Error: Could not find version in TOC file"
+  exit 1
+fi
+
+OUT_FILE="Soundtrack.$VERSION.zip"
+
+rm -f $OUT_FILE
 cd src
-zip -r ../$OUT_FILE Soundtrack -x "*.iml" -x "*.hexdumptmp*" -x "*MyTracks.lua*" -x "*.pyc*" -x "*LegacyLibraryGeneration/META-INF/*" -x "*LegacyLibraryGeneration/src/*" -x "*.DS_Store"
+zip -r ../$OUT_FILE Soundtrack -x "*.iml" -x "*.hexdumptmp*" -x "*MyTracks.lua*" -x "*.pyc*" -x "*LegacyLibraryGeneration/META-INF/*" -x "*LegacyLibraryGeneration/src/*" -x "*.DS_Store" -x "*/.git" -x "*/.git/*" -x "*.gitignore" -x "*.gitattributes"
 cd ..
diff --git a/scripts/packageAndInstall b/scripts/packageAndInstall
--- a/scripts/packageAndInstall
+++ b/scripts/packageAndInstall
@@ -15,7 +15,17 @@ fi
 echo "Game folder: $GAME_FOLDER"
 echo "WoW root path: $WOW_ROOT_PATH"
 
+# Extract version from TOC file
+VERSION=$(grep "^## Version:" src/Soundtrack/Soundtrack-Mainline.toc | sed 's/^## Version: *//')
+
+if [ -z "$VERSION" ]; then
+  echo "Error: Could not find version in TOC file"
+  exit 1
+fi
+
+ZIP_FILE="Soundtrack.$VERSION.zip"
+
 rm -rf "$WOW_ROOT_PATH/$GAME_FOLDER/Interface/Addons/Soundtrack"
 rm -rf "$WOW_ROOT_PATH/$GAME_FOLDER/Interface/Addons/SoundtrackMusic/LegacyLibraryGeneration"
-./scripts/package SoundtrackTest.0.4.zip
-./scripts/installFromZip SoundtrackTest.0.4.zip "$GAME_FOLDER" "$WOW_ROOT_PATH"
+./scripts/package
+./scripts/installFromZip "$ZIP_FILE" "$GAME_FOLDER" "$WOW_ROOT_PATH"
